// POSTS
export const CREATE_POST = 'POSTS/CREATE';
export const DELETE_POST = 'POSTS/DELETE';

// AUTH
export const UPDATE_UID = 'UPDATE_UID'

// NOTIFICATIONS
export const UPDATE_NOTIFICATIONS = 'UPDATE_NOTIFICATIONS';
export const SET_NOTIFICATION_STATUS = 'SET_NOTIFICATION_STATUS';
export const SET_NOTIFICATION_ALERT = 'SET_NOTIFICATION_ALERT';

// PROFILE
export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE';